### ISSUE TITLE
Windows11 报错 Unmapped relationship: 7

### ISSUE THREAD

**Issue by baochangying** [0xcaffebabe/seeaw4#5]
Exception in thread "pool-2-thread-1" java.lang.IllegalStateException: Unmapped relationship: 7
	at com.sun.jna.platform.win32.WinNT$SYSTEM_LOGICAL_PROCESSOR_INFORMATION_EX.fromPointer(WinNT.java:2999)
	at com.sun.jna.platform.win32.Kernel32Util.getLogicalProcessorInformationEx(Kernel32Util.java:715)
	at oshi.hardware.platform.windows.WindowsCentralProcessor.getLogicalProcessorInformationEx(WindowsCentralProcessor.java:310)
	at oshi.hardware.platform.windows.WindowsCentralProcessor.initProcessorCounts(WindowsCentralProcessor.java:300)
	at oshi.hardware.common.AbstractCentralProcessor.<init>(AbstractCentralProcessor.java:69)
	at oshi.hardware.platform.windows.WindowsCentralProcessor.<init>(WindowsCentralProcessor.java:70)
	at oshi.hardware.platform.windows.WindowsHardwareAbstractionLayer.createProcessor(WindowsHardwareAbstractionLayer.java:60)
	at oshi.util.Memoizer$1.get(Memoizer.java:84)
	at oshi.hardware.common.AbstractHardwareAbstractionLayer.getProcessor(AbstractHardwareAbstractionLayer.java:63)
	at wang.ismy.seeaw4.terminal.Terminal.getSystemInfo(Terminal.java:81)
	at wang.ismy.seeaw4.client.command.ClientCommandHandler.systemInfo(ClientCommandHandler.java:88)
	at wang.ismy.seeaw4.client.command.ClientCommandHandler.process(ClientCommandHandler.java:49)
	at wang.ismy.seeaw4.client.message.chain.ClientCommandMessageChain.lambda$process$0(ClientCommandMessageChain.java:36)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

**Comment by baochangying** [comment]
查看依赖是slf4j的版本问题，升级后得到解决。
